export const dataRestaurants = [
  {
    name: "The Cheesecake Factory",
    "website link": "https://www.thecheesecakefactory.com/",
    address: "123 Main Street, Anytown, USA",
    phone: "(555) 555-5555",
    typeRestaurant: "American",
  },
  {
    name: "P.F. Chang's",
    "website link": "https://www.pfchangs.com/",
    address: "456 Elm Street, Anytown, USA",
    phone: "(555) 555-5556",
    typeRestaurant: "Chinese",
  },
  {
    name: "Dunkin' Donuts",
    "website link": "https://www.dunkin.com/",
    address: "789 Oak Street, Anytown, USA",
    phone: "(555) 555-5557",
    typeRestaurant: "Coffee and doughnuts",
  },
  {
    name: "McDonald's",
    "website link": "https://www.mcdonalds.com/",
    address: "1011 Pine Street, Anytown, USA",
    phone: "(555) 555-5558",
    typeRestaurant: "Fast food",
  },
  {
    name: "Subway",
    "website link": "https://www.subway.com/",
    address: "1112 Birch Street, Anytown, USA",
    phone: "(555) 555-5559",
    typeRestaurant: "Sandwiches",
  },
  {
    name: "Chipotle Mexican Grill",
    "website link": "https://www.chipotle.com/",
    address: "1234 Elm Street, Anytown, USA",
    phone: "(555) 555-5560",
    typeRestaurant: "Mexican",
  },
  {
    name: "Domino's Pizza",
    "website link": "https://www.dominos.com/",
    address: "5678 Elm Street, Anytown, USA",
    phone: "(555) 555-5561",
    typeRestaurant: "Pizza",
  },
  {
    name: "Starbucks",
    "website link": "https://www.starbucks.com/",
    address: "9012 Elm Street, Anytown, USA",
    phone: "(555) 555-5562",
    typeRestaurant: "Coffee and pastries",
  },
  {
    name: "Taco Bell",
    "website link": "https://www.tacobell.com/",
    address: "101 Elm Street, Anytown, USA",
    phone: "(555) 555-5563",
    typeRestaurant: "Mexican",
  },
  {
    name: "Burger King",
    "website link": "https://www.bk.com/",
    address: "112 Elm Street, Anytown, USA",
    phone: "(555) 555-5564",
    typeRestaurant: "Fast food",
  },
];
